name: Sync labels on CI

on:
  push:
    branches: ["main"]
    paths:
      - .github/labels.yml

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.6.0
    - name: Sync labels
      uses: b4b4r07/github-labeler@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
